# Day -12

<!-- Activity 1 -->

1. Write a fuction that intentionally thows an error and use a try-catch block to handle the error and log an approapriate message to the console.
2. CReat a function that divides two numbers and throws an error if the denominator is zero. Use a try-catch block to handle the error

<!-- Activtity2  -->

1. write a script that includes a try-catch blocl and a finally block . Log message in the try, catch, and finally blocks to observe the execution flow.

<!-- Activity 3 -->

1. create a custom error class that extends the built-in-Error class. Throw an instance of this custom error in a functino and handle it using a try -catch block.

2. write a function that validate user input(eg. checking if a string is not empty ) and throws a custom error if the validation fails. Handle the custom error using try-catch block.

<!-- Activity 4 -->

1. create a promise that randomly resolve or reject . Use catch() to handle the rejection and log an appropriate message to the console.
2. Use try-catch within an async function to handle errors from a promise that randomly resolve or rejects and log the error message.

<!-- Activity5  -->

1. Use the fetch API to request data from and invalid URL and handle the error using catch() . Log an appropriate error message to the console.
2. Use the fetch API to request data from an invalid URL withing an async function and handle the error using try-cathc . Log an appropriate error message
